In [1]:
import sys

sys.path.append("..")

import numpy as np

# local module
import src.array_data as array_data

In [2]:
arr = array_data.TimePoseSequence(10)
arr

<TimePoseSequence contains 10 rows>

---
Timestamps

In [3]:
# unit: nanosecond
# 3600 * 1e9 nanoseconds -> 1 hour
arr.timestamps = np.arange(10) * 3600 * 1e9
arr.timestamps

array([             0,  3600000000000,  7200000000000, 10800000000000,
       14400000000000, 18000000000000, 21600000000000, 25200000000000,
       28800000000000, 32400000000000])

In [4]:
arr.datetime

DatetimeIndex(['1970-01-01 00:00:00', '1970-01-01 01:00:00',
               '1970-01-01 02:00:00', '1970-01-01 03:00:00',
               '1970-01-01 04:00:00', '1970-01-01 05:00:00',
               '1970-01-01 06:00:00', '1970-01-01 07:00:00',
               '1970-01-01 08:00:00', '1970-01-01 09:00:00'],
              dtype='datetime64[ns]', freq=None)

---
Pose

In [5]:
arr.xyz = np.arange(30).reshape(10, 3)
arr.xyz

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [6]:
arr.quaternion = np.vstack([
    np.random.rand(10),  # x
    np.random.rand(10),  # y
    np.random.rand(10),  # z
    np.ones(10),         # W
]).T

In [7]:
arr.quaternion

array([[0.21690593, 0.18086447, 0.42296795, 1.        ],
       [0.00722773, 0.19379819, 0.77089639, 1.        ],
       [0.99904804, 0.8598604 , 0.74736511, 1.        ],
       [0.2647337 , 0.48048745, 0.83377485, 1.        ],
       [0.6190132 , 0.8756613 , 0.85752145, 1.        ],
       [0.06379236, 0.21858379, 0.13720506, 1.        ],
       [0.4840815 , 0.98545339, 0.05861947, 1.        ],
       [0.32378869, 0.65393303, 0.78282093, 1.        ],
       [0.50024423, 0.250603  , 0.44304746, 1.        ],
       [0.17726256, 0.61242234, 0.06160832, 1.        ]])

In [8]:
arr.R.shape, arr.R

((10, 3, 3),
 array([[[ 0.66374795, -0.60975443,  0.43317225],
         [ 0.73442833,  0.64096785, -0.22310367],
         [-0.14161103,  0.46621858,  0.87326202]],
 
        [[ 0.2256359 , -0.94307226,  0.24434229],
         [ 0.94650562,  0.27160159,  0.17424029],
         [-0.23068494,  0.19195649,  0.95390627]],
 
        [[ 0.21243325,  0.06776477,  0.97482309],
         [ 0.9747581 ,  0.05543316, -0.21627253],
         [-0.06869318,  0.99616018, -0.05427842]],
 
        [[ 0.07215715, -0.70794257,  0.70257431],
         [ 0.9628379 ,  0.23325291,  0.13614791],
         [-0.26026241,  0.66664113,  0.6984648 ]],
 
        [[-0.04122562, -0.21867758,  0.97492593],
         [ 0.97013541,  0.22467738,  0.09141858],
         [-0.23903499,  0.94957895,  0.2028844 ]],
 
        [[ 0.87558467, -0.2302496 ,  0.42466058],
         [ 0.28234382,  0.9572331 , -0.06314073],
         [-0.39196104,  0.17518535,  0.90314818]],
 
        [[ 0.11760673,  0.37885126,  0.91795445],
         [ 0.485003

---
Indexing

In [9]:
arr.datetime

DatetimeIndex(['1970-01-01 00:00:00', '1970-01-01 01:00:00',
               '1970-01-01 02:00:00', '1970-01-01 03:00:00',
               '1970-01-01 04:00:00', '1970-01-01 05:00:00',
               '1970-01-01 06:00:00', '1970-01-01 07:00:00',
               '1970-01-01 08:00:00', '1970-01-01 09:00:00'],
              dtype='datetime64[ns]', freq=None)

In [10]:
foo = arr[:4]
foo, foo.datetime, foo.xyz

(<TimePoseSequence contains 4 rows>,
 DatetimeIndex(['1970-01-01 00:00:00', '1970-01-01 01:00:00',
                '1970-01-01 02:00:00', '1970-01-01 03:00:00'],
               dtype='datetime64[ns]', freq=None),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [11]:
foo = arr[[1, 3, 7]]
foo, foo.datetime, foo.xyz

(<TimePoseSequence contains 3 rows>,
 DatetimeIndex(['1970-01-01 01:00:00', '1970-01-01 03:00:00',
                '1970-01-01 07:00:00'],
               dtype='datetime64[ns]', freq=None),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [21, 22, 23]]))

In [12]:
foo.index

array([1, 3, 7])